# Generated by Django 3.1.2 on 2021-05-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('song', models.FileField(upload_to='static/audio/')),
                ('first_prompt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_no', models.IntegerField(default=1)),
                ('yesurl', models.FileField(upload_to='static/audio/')),
                ('nourl', models.FileField(upload_to='static/audio/')),
                ('prompturl', models.FileField(upload_to='static/audio/')),
                ('next_prompt', models.FloatField(default=0)),
                ('previous_prompt', models.FloatField(default=0)),
                ('no_action', models.FloatField(default=0)),
                ('prompt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
    ]
